apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-config
  namespace: your-namespace
data:
  ENV: development
  DATABASE_URL: "postgresql://postgres:secure_password_2025@postgres:5432/user-service-db"
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  API_GATEWAY_URL: http://api-gateway:9490
  LOG_LEVEL: debug