apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: your-namespace  # Replace with your actual namespace
spec:
  type: ClusterIP
  ports:
    - port: 9490
      targetPort: 9490
  selector:
    app: api-gateway  # Ensure this matches the label in the deployment
