apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  type: LoadBalancer
  ports:
    - port: 9496
      targetPort: 9496
  selector:
    app: notification-service