apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  type: LoadBalancer
  ports:
    - port: 9492
      targetPort: 9492
  selector:
    app: account-service