apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
    - port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app: kafka