apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
    - name: broker        # Added port name
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: controller    # Added port name
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app: kafka