apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc # Name of the PVC
  labels:
    app: redis
spec:
  accessModes:
    - ReadWriteOnce # The volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 1Gi # Request 1Gi of storage
