apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/kafka
  - ../../base/kafdrop
  - ../../base/postgres
  - ../../base/api-gateway
  - ../../base/account-service
  - ../../base/namespace
  # - ../../base/vault
  - ../../base/user-service
  - ../../base/notification-service
  - ../../base/front-end
  - ../../base/redis # Include Redis configuration
  - ../../base/ingress-controller   

configMapGenerator:
  - name: prod-config
    files:
      - config.yaml

images:
  - name: bjitpdmad/api-gateway
    newTag: latest
  - name: bjitpdmad/account-service
    newTag: latest
  - name: bjitpdmad/account-service
    newTag: latest
  - name: obsidiandynamics/kafdrop
    newTag: latest
  - name: bitnami/kafka
    newTag: latest
  - name: postgres
    newTag: latest
  - name: hashicorp/vault
    newTag: 1.13.3
  - name: bjitpdmad/user-service
    newTag: latest
  - name: bjitpdmad/notification-service
    newTag: latest
  - name: bjitpdmad/db-frontend
    newTag: latest

namespace: digital-bank
