apiVersion: v1
kind: Service
metadata:
  name: digital-banking-frontend
  labels:
    app: digital-banking-frontend
spec:
  ports:
    - port: 80
      targetPort: 80  # This should match your container port (80)
  selector:
    app: digital-banking-frontend