apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml

nameSuffix: -ingress-controller

commonLabels:
  app: ingress-controller

images:
  - name: nginx-ingress-controller
    newTag: latest