apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-banking-frontend
  namespace: digital-bank
spec:
  template:
    metadata:
      labels:
        app: digital-banking-frontend
        version: v1
