apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  namespace: digital-bank  # Replace with your actual namespace if needed
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: kafdrop  # Ensure this matches the labels in your Kafdrop deployment
