apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: vault:latest
        ports:
        - containerPort: 8200
          name: vaultport
          protocol: TCP
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: "dev-root-token"
        - name: VAULT_DEV_LISTEN_ADDRESS
          value: "0.0.0.0:8200"
        volumeMounts:
        - name: vault-data
          mountPath: /vault/data
        - name: vault-config
          mountPath: /vault/config
        - name: vault-init-script
          mountPath: /vault/init
        command: ["/bin/sh"]
        args:
        - -c
        - |
          vault server -config=/vault/config/vault.json &
          sleep 5
          sh /vault/init/init.sh
      volumes:
      - name: vault-data
        persistentVolumeClaim:
          claimName: vault-pvc
      - name: vault-config
        configMap:
          name: vault-config
      - name: vault-init-script
        configMap:
          name: vault-init-script