apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: digital-bank
data:
  vault.json: |
    {
      "listener": {
        "tcp": {
          "address": "0.0.0.0:8200",
          "tls_disable": 1
        }
      },
      "storage": {
        "file": {
          "path": "/vault/data"
        }
      },
      "ui": true,
      "disable_mlock": true,
      "api_addr": "http://vault.digital-bank.svc.cluster.local:8200"
    }