name: Deploy to Amazon EKS with Helm

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: MY_AWS_REGION                   # e.g., us-west-1
  ECR_REPOSITORY: MY_ECR_REPOSITORY           # Your ECR repository name
  EKS_CLUSTER_NAME: MY_EKS_CLUSTER            # EKS cluster name
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  HELM_CHART_NAME: my-app                     # Your Helm chart directory name
  IMAGE_TAG: ${{ github.sha }}
  KUBECONFIG_FILE: kubeconfig-${{ github.run_id }}  # Unique kubeconfig file per run

permissions:
  contents: read
  id-token: write  # Required for OIDC authentication

jobs:
  deploy:
    name: Deploy with Helm
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker Image
      run: |
        docker build --platform linux/amd64 -t ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
        docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

    - name: Set Up EKS Access
      run: |
        aws eks update-kubeconfig \
          --region ${{ env.AWS_REGION }} \
          --name ${{ env.EKS_CLUSTER_NAME }} \
          --kubeconfig ${{ env.KUBECONFIG_FILE }}

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.13.2'  # Specify Helm version

    - name: Create Helm Chart (if not exists)
      run: |
        if [ ! -d "./charts/${{ env.HELM_CHART_NAME }}" ]; then
          helm create ./charts/${{ env.HELM_CHART_NAME }}
        fi

    - name: Package Helm Chart
      run: |
        helm dependency update ./charts/${{ env.HELM_CHART_NAME }}  # Update chart dependencies
        helm package ./charts/${{ env.HELM_CHART_NAME }} -d ./charts  # Package chart

    - name: Deploy Helm Chart
      run: |
        helm upgrade --install \
          ${{ env.HELM_CHART_NAME }} \
          ./charts/${{ env.HELM_CHART_NAME }} \
          --namespace default \
          --set image.repository=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }} \
          --set image.tag=${{ env.IMAGE_TAG }} \
          --atomic \  # Rollback on failure
          --wait      # Wait for deployment to complete
      env:
        KUBECONFIG: ${{ env.KUBECONFIG_FILE }}